default_stages: [commit, push]
repos:
  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo:  https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        exclude: ^docs/

  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.3
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
