language: python
python:
 - "3.6"
 - "3.5"
 - "3.4"
env:
 - TOX_ENV=travis
 - TOX_ENV=docs
install:
 - pip install tox
script:
 - tox -e $TOX_ENV
before_install:
  - pip install codecov
after_success:
  - codecov
