language: python
python: 3.6
env:
 - TOX_ENV=py34-travis
 - TOX_ENV=py35-travis
 - TOX_ENV=py36-travis
 - TOX_ENV=docs
install:
 - pip install tox
script:
 - tox -e $TOX_ENV
before_install:
  - pip install codecov
after_success:
  - codecov
